export const THEMES = [
  {
    name: 'Deep Blue',
    background: '#0a0a1a',
    backgroundGradientEnd: '#1a0a2e',
    nodeDefault: '#1e3a5f',
    nodeDefaultBorder: '#2a6db5',
    nodeCurrent: '#0d47a1',
    nodeCurrentBorder: '#42a5f5',
    nodeTarget: '#1a237e',
    nodeTargetBorder: '#7c4dff',
    nodeVisited: '#1a1a2e',
    nodeVisitedBorder: '#333355',
    nodeCorrect: '#1b5e20',
    nodeCorrectBorder: '#66bb6a',
    nodeWrong: '#b71c1c',
    nodeWrongBorder: '#ef5350',
    textPrimary: '#ffffff',
    textSecondary: '#90caf9',
    textMuted: '#546e7a',
    edgeLine: '#1e3a5f',
    edgeLineActive: '#42a5f5',
    hudBackground: 'rgba(0,0,0,0.7)',
    swipeLeft: '#ef5350',
    swipeRight: '#66bb6a',
    gold: '#ffd700',
    particle: '#42a5f5',
  },
  {
    name: 'Emerald Ember',
    background: '#041814',
    backgroundGradientEnd: '#0f2b24',
    nodeDefault: '#114b3f',
    nodeDefaultBorder: '#1fa37a',
    nodeCurrent: '#0f6b56',
    nodeCurrentBorder: '#2bd3a4',
    nodeTarget: '#133040',
    nodeTargetBorder: '#ffb74d',
    nodeVisited: '#0a1a16',
    nodeVisitedBorder: '#164237',
    nodeCorrect: '#1b5e20',
    nodeCorrectBorder: '#66bb6a',
    nodeWrong: '#b71c1c',
    nodeWrongBorder: '#ef5350',
    textPrimary: '#e7fff8',
    textSecondary: '#9fe8d7',
    textMuted: '#5d8c81',
    edgeLine: '#114b3f',
    edgeLineActive: '#2bd3a4',
    hudBackground: 'rgba(0,0,0,0.65)',
    swipeLeft: '#ef5350',
    swipeRight: '#66bb6a',
    gold: '#ffb74d',
    particle: '#2bd3a4',
  },
  {
    name: 'Violet Pulse',
    background: '#150a1f',
    backgroundGradientEnd: '#2a0a2e',
    nodeDefault: '#3a1e5f',
    nodeDefaultBorder: '#a342f5',
    nodeCurrent: '#5c2d91',
    nodeCurrentBorder: '#d56bff',
    nodeTarget: '#1e2a4a',
    nodeTargetBorder: '#4dd0e1',
    nodeVisited: '#1a1026',
    nodeVisitedBorder: '#3b224f',
    nodeCorrect: '#1b5e20',
    nodeCorrectBorder: '#66bb6a',
    nodeWrong: '#b71c1c',
    nodeWrongBorder: '#ef5350',
    textPrimary: '#f7ecff',
    textSecondary: '#cbb2ff',
    textMuted: '#7c6b8f',
    edgeLine: '#3a1e5f',
    edgeLineActive: '#d56bff',
    hudBackground: 'rgba(0,0,0,0.68)',
    swipeLeft: '#ff6b6b',
    swipeRight: '#7dffb3',
    gold: '#ffd54f',
    particle: '#d56bff',
  },
  {
    name: 'Solar Flare',
    background: '#1a0a0a',
    backgroundGradientEnd: '#2e140a',
    nodeDefault: '#5f2a1e',
    nodeDefaultBorder: '#f58f42',
    nodeCurrent: '#7a1c1c',
    nodeCurrentBorder: '#ff7043',
    nodeTarget: '#1b2a4a',
    nodeTargetBorder: '#29b6f6',
    nodeVisited: '#241010',
    nodeVisitedBorder: '#4a2a2a',
    nodeCorrect: '#1b5e20',
    nodeCorrectBorder: '#66bb6a',
    nodeWrong: '#b71c1c',
    nodeWrongBorder: '#ef5350',
    textPrimary: '#fff4ea',
    textSecondary: '#ffc49c',
    textMuted: '#9b7a6a',
    edgeLine: '#5f2a1e',
    edgeLineActive: '#ffb74d',
    hudBackground: 'rgba(0,0,0,0.7)',
    swipeLeft: '#ff8a80',
    swipeRight: '#81c784',
    gold: '#ffcc80',
    particle: '#ffb74d',
  },
] as const;

export type Theme = (typeof THEMES)[number];

export const COLORS: Theme = THEMES[0];

export function getThemeForLevel(level: number): Theme {
  if (level <= 3) return THEMES[0];
  if (level <= 6) return THEMES[1];
  if (level <= 9) return THEMES[2];
  return THEMES[3];
}

export const FONTS = {
  regular: 'SpaceMono',
  sizes: {
    nodeNumber: 32,
    targetLabel: 16,
    targetNumber: 48,
    score: 20,
    level: 18,
    hud: 14,
  },
} as const;

export const LAYOUT = {
  nodeRadius: 52,
  nodeStartScale: 0.15,
  nodeEndScale: 1.0,
  horizonY: 0.18,       // fraction of screen height where nodes originate
  swipeZoneY: 0.72,     // fraction of screen height where node is largest
  swipeZoneHeight: 120,
  treeLineWidth: 2,
  activeTreeLineWidth: 3,
} as const;
